trigger:
- master
pool:
  vmImage: "ubuntu-latest"
variables:
  - name: modulePath
    value: https://github.com/Tharani245/pipelines-go
    
steps:
  - task: GoTool@0
    inputs:
      version: '1.13.5'

  - task: Go@0
    inputs:
      command: 'build'
      workingDirectory: '$(modulePath)'
  
  - task: CopyFiles@2
    inputs:
      Contents: '**'
      TargetFolder: '$(build.artifactstagingdirectory)'
  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      